### ISSUE TITLE
运行install后依赖安装不上

### ISSUE THREAD

**Issue by shangdev** [QC2168/vite-plugin-utools#1]
```
const install = require("@qc2168/vite-plugin-utools").install;
install(["./dist/preload.js"]);
```

执行以上代码后，依赖没安装上。项目地址：https://github.com/shangdev/utools-php-unserialize

**Comment by QC2168** [comment]
试了下，preload.js中没有第三方依赖，所以不会安装

**Comment by QC2168** [comment]
![image](https://github.com/user-attachments/assets/011a8c4e-faec-481d-ac69-79713fe71763)
![image](https://github.com/user-attachments/assets/b20724c0-2e5a-4fb9-9aa9-2a1f6c964515)

**Comment by shangdev** [comment]
![image](https://github.com/user-attachments/assets/2b6dd8e6-60d6-4de8-b643-4bd6b9aa8b60)

@QC2168 之前这样写的时候install不上，所以挪到了app.vue里

**Comment by QC2168** [comment]
试试最新版本的插件版本呢 V1.6.1

**Comment by shangdev** [comment]
> 试试最新版本的插件版本呢 V1.6.1

麻烦再看下项目地址：https://github.com/shangdev/utools-php-unserialize，执行node install.js后提示：traverse is not a function
@QC2168

**Comment by QC2168** [comment]
@shangdev 需要使用esm的方式引入

**Comment by QC2168** [comment]
```js
import { install } from '@qc2168/vite-plugin-utools'

install(['./dist/preload.js'])

```

**Comment by shangdev** [comment]
![image](https://github.com/user-attachments/assets/e2ab0287-5568-41a7-812f-aeecd98f2f3a)

@QC2168 一样的，运行后只生成了package.json，但是没有preload中的依赖包

**Comment by QC2168** [comment]
可以提供一个最小可复现的仓库吗

**Comment by shangdev** [comment]
@QC2168 这个仓库就是：https://github.com/shangdev/utools-php-unserialize.git
开源php序列号项目，复现步骤：
1、pnpm install
2、pnpm build
3、node install.js

**Comment by QC2168** [comment]
好，我看看

**Comment by QC2168** [comment]
![image](https://github.com/user-attachments/assets/1a3ebd8c-ffa2-46b0-b5f3-e56995939864)

**Comment by QC2168** [comment]
问题已经修复，稍等后我发个包

**Comment by QC2168** [comment]
@shangdev 请更新插件版本`1.6.2`即可
